- name: Install and Configure WebServer
  hosts: aws_ec2
  become: yes  # Use sudo for privileges elevation
  vars:
    welcome_message: "<h1>Welcome to ACS730 PROJECT!</h1><h2>My private IP is {{ ansible_default_ipv4.address }}</h2><h2>Built by Kusal Thiwanka using Ansible!</h2><img src='https://kusal-webserver.s3.us-east-1.amazonaws.com/images/kusal.png?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjENL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQDn0tzEGoui4QtKUwfx01pG8t60VuzlIRZHRcJSzD1s%2BgIgMqW2xhrhl%2F%2B1Lu7FKqGRAU3D5Ha6lMTQ3w%2Fr8DVgCdQqgQMIGxAAGgw3NDIyODY2MzYxOTgiDGmZLOoP%2BBFQ3lUK%2BSreAjXbgFZ6ycsSQSi64D0RR4IpDhcGnKO6RZsWj8Xub1Tp4NC6BGFBpt5na5q8ewVo3XoyiYW%2BRd91PoE3a2GxhliWxmuUmsUP4flaE7emj6fM%2B%2FS449p4%2Bv4CNTYghwhqfmKu6xgfzu0HlyfMIv%2FQEWOCBVWkiX0pJ%2FtCA1b3V44G2PfhUVKaIzdt8IJ5x5lB3Nu0VquytP1HRagobxHYZW%2BR9ZGiM907iC62lbjONYRazchjjiGGBCYxLsBrb3xXuMrrKCAMgN8KG86O2OuQEwrTrjLl1SWWWUY4y5biEDP%2FWXpg2wMabAk08lxWw0GGbFoWhP%2BvCwQkDd9ieQP%2Fqd%2Bja4tpRk4E1VQSu3ndsGVKITpr7UeeOToKx%2FppnX%2BhrPG%2BEMHLq3N9NFikj28W6lvHyPDQcY%2BYekrT7M64eyC8xmhbm%2FOACRMzQ9MKatDD3nZFnYLZA3iXQu40DCtNMKzhibEGOocC1d2uff6FjO07%2F%2BLn01VZnIL%2Bl3IpmVpI9b1ae%2BlAlGawuIbvBIdyQJgdukNI4Liz1kldJr8gI8fpVkPlw9WmqbKIQfgE7QDR1x3EU66IQdarQseq7%2BykCTMYu17pClt8aZbcPKINwd3QzcGBYXg3a7dLCXsrIddkjDkvJUjwkFWDjNFQURElM50O%2FXkKw0gcdUqkF8MJO8WP7SGUIMHw34HSRHEae%2Fma0xCO7qNNObwgB8b4j6dp2E37jXh6eQjtQt0tsLxdUAfGjoio6a1FXdrLu0AoBktmdshowHH5EGzhCF0lASaJgH6lH6NU%2Bz2Wk2MJSzc8juKqXhyvYP6hBKT8mOlzhNA%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240419T183022Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIA2ZU53GSTOHE4WE7N%2F20240419%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=82ead5466a988829aba8a6a9ec8be3dc27befd7a87ebe2f0320479cf973a2ea6' alt='Prject Architecture'>"

  tasks:
    - name: Update all packages to their latest version
      yum:
        name: "*"
        state: latest

    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Create index.html with custom welcome message
      copy:
        dest: /var/www/html/index.html
        content: "{{ welcome_message }}"
        owner: apache
        group: apache
        mode: '0644'

    - name: Ensure httpd is started and enabled on boot
      systemd:
        name: httpd
        state: started
        enabled: yes